FROM node:18-alpine

WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .
COPY tsconfig.json .

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

CMD ["node", "dist/index.js"]
